# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1285, 742)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(20, 20, 20);")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.GUI_Title = QtWidgets.QLabel(self.centralWidget)
        self.GUI_Title.setGeometry(QtCore.QRect(330, 10, 640, 51))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setItalic(False)
        self.GUI_Title.setFont(font)
        self.GUI_Title.setStyleSheet("color: rgb(171, 171, 171);")
        self.GUI_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.GUI_Title.setObjectName("GUI_Title")
        self.frame = QtWidgets.QFrame(self.centralWidget)
        self.frame.setGeometry(QtCore.QRect(50, 590, 1191, 121))
        self.frame.setStyleSheet("background-color:rgb(88, 88,  88);")
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.upperCalLabel = QtWidgets.QLabel(self.frame)
        self.upperCalLabel.setGeometry(QtCore.QRect(640, 10, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.upperCalLabel.setFont(font)
        self.upperCalLabel.setStyleSheet("color:rgb(220, 220, 220);")
        self.upperCalLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.upperCalLabel.setObjectName("upperCalLabel")
        self.lowerCalLabel = QtWidgets.QLabel(self.frame)
        self.lowerCalLabel.setGeometry(QtCore.QRect(940, 10, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lowerCalLabel.setFont(font)
        self.lowerCalLabel.setStyleSheet("color:rgb(220, 220, 220);")
        self.lowerCalLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lowerCalLabel.setObjectName("lowerCalLabel")
        self.pressTempToggleButton = QtWidgets.QPushButton(self.centralWidget)
        self.pressTempToggleButton.setGeometry(QtCore.QRect(1090, 20, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(False)
        self.pressTempToggleButton.setFont(font)
        self.pressTempToggleButton.setStyleSheet("background-color: rgb(255, 127, 0);")
        self.pressTempToggleButton.setObjectName("pressTempToggleButton")
        self.numGraphToggleButton = QtWidgets.QPushButton(self.frame)
        self.numGraphToggleButton.setGeometry(QtCore.QRect(50, 20, 211, 81))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setItalic(False)
        self.numGraphToggleButton.setFont(font)
        self.numGraphToggleButton.setStyleSheet("background-color: rgb(0, 167, 255);")
        self.numGraphToggleButton.setObjectName("numGraphToggleButton")
        self.upperCalButton = QtWidgets.QPushButton(self.frame)
        self.upperCalButton.setGeometry(QtCore.QRect(730, 40, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.upperCalButton.setFont(font)
        self.upperCalButton.setStyleSheet("background-color: rgb(0, 167, 255);")
        self.upperCalButton.setDefault(False)
        self.upperCalButton.setObjectName("upperCalButton")
        self.lowerCalButton = QtWidgets.QPushButton(self.frame)
        self.lowerCalButton.setGeometry(QtCore.QRect(1030, 40, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lowerCalButton.setFont(font)
        self.lowerCalButton.setStyleSheet("background-color: rgb(0, 167, 255);")
        self.lowerCalButton.setAutoDefault(False)
        self.lowerCalButton.setDefault(False)
        self.lowerCalButton.setFlat(False)
        self.lowerCalButton.setObjectName("lowerCalButton")
        self.upperCalField = QtWidgets.QTextEdit(self.frame)
        self.upperCalField.setGeometry(QtCore.QRect(630, 40, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.upperCalField.setFont(font)
        self.upperCalField.setStyleSheet("background-color: rgb(171, 171, 171);")
        self.upperCalField.setObjectName("upperCalField")
        self.lowerCalField = QtWidgets.QTextEdit(self.frame)
        self.lowerCalField.setGeometry(QtCore.QRect(930, 40, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lowerCalField.setFont(font)
        self.lowerCalField.setStyleSheet("background-color: rgb(171, 171, 171);")
        self.lowerCalField.setObjectName("lowerCalField")
        self.calibrateButton = QtWidgets.QPushButton(self.frame)
        self.calibrateButton.setGeometry(QtCore.QRect(490, 20, 211, 81))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.calibrateButton.setFont(font)
        self.calibrateButton.setStyleSheet("background-color: rgb(0, 167, 255);")
        self.calibrateButton.setCheckable(False)
        self.calibrateButton.setAutoRepeat(False)
        self.calibrateButton.setDefault(False)
        self.calibrateButton.setFlat(False)
        self.calibrateButton.setObjectName("calibrateButton")
        self.logButton = QtWidgets.QPushButton(self.frame)
        self.logButton.setGeometry(QtCore.QRect(930, 20, 211, 81))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.logButton.setFont(font)
        self.logButton.setStyleSheet("background-color: rgb(0, 167, 255);")
        self.logButton.setCheckable(False)
        self.logButton.setAutoRepeat(False)
        self.logButton.setDefault(False)
        self.logButton.setFlat(False)
        self.logButton.setObjectName("logButton")
        self.pressureGraph = CustomPressWidget(self.centralWidget)
        self.pressureGraph.setGeometry(QtCore.QRect(30, 70, 1211, 471))
        self.pressureGraph.setObjectName("pressureGraph")
        self.pressureValue = QtWidgets.QLabel(self.centralWidget)
        self.pressureValue.setGeometry(QtCore.QRect(60, 60, 1191, 431))
        #
        self.temperatureGraph = CustomTempWidget(self.centralWidget)
        self.temperatureGraph.setGeometry(QtCore.QRect(30, 70, 1211, 471))
        self.temperatureGraph.setObjectName("temperatureGraph")
        self.temperatureGraph.hide()




        font = QtGui.QFont()
        font.setPointSize(35)
        self.tempLabel0 = QtWidgets.QLabel(self.centralWidget)
        self.tempLabel0.setGeometry(QtCore.QRect(60, 100, 250, 100))
        self.tempLabel0.setFont(font)
        self.tempLabel0.setStyleSheet("color:rgb(171, 171, 171);")
        self.tempLabel0.setAlignment(QtCore.Qt.AlignCenter)
        self.tempLabel0.setObjectName("tempLabel0")

        self.tempLabel1 = QtWidgets.QLabel(self.centralWidget)
        self.tempLabel1.setGeometry(QtCore.QRect(360, 100, 250, 100))
        self.tempLabel1.setFont(font)
        self.tempLabel1.setStyleSheet("color:rgb(171, 171, 171);")
        self.tempLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.tempLabel1.setObjectName("tempLabel1")

        self.tempLabel2 = QtWidgets.QLabel(self.centralWidget)
        self.tempLabel2.setGeometry(QtCore.QRect(660, 100, 250, 100))
        self.tempLabel2.setFont(font)
        self.tempLabel2.setStyleSheet("color:rgb(171, 171, 171);")
        self.tempLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.tempLabel2.setObjectName("tempLabel2")

        self.tempLabel3 = QtWidgets.QLabel(self.centralWidget)
        self.tempLabel3.setGeometry(QtCore.QRect(960, 100, 250, 100))
        self.tempLabel3.setFont(font)
        self.tempLabel3.setStyleSheet("color:rgb(171, 171, 171);")
        self.tempLabel3.setAlignment(QtCore.Qt.AlignCenter)
        self.tempLabel3.setObjectName("tempLabel3")

        font = QtGui.QFont()
        font.setPointSize(86)
        self.temperatureValue0 = QtWidgets.QLabel(self.centralWidget)
        self.temperatureValue0.setGeometry(QtCore.QRect(60, 180, 250,200))
        self.temperatureValue0.setFont(font)
        self.temperatureValue0.setStyleSheet("color:rgb(171, 171, 171);")
        self.temperatureValue0.setAlignment(QtCore.Qt.AlignCenter)
        self.temperatureValue0.setObjectName("temperatureValue0")

        self.temperatureValue1 = QtWidgets.QLabel(self.centralWidget)
        self.temperatureValue1.setGeometry(QtCore.QRect(360, 180, 250,200))
        self.temperatureValue1.setFont(font)
        self.temperatureValue1.setStyleSheet("color:rgb(171, 171, 171);")
        self.temperatureValue1.setAlignment(QtCore.Qt.AlignCenter)
        self.temperatureValue1.setObjectName("temperatureValue1")

        self.temperatureValue2 = QtWidgets.QLabel(self.centralWidget)
        self.temperatureValue2.setGeometry(QtCore.QRect(660, 180, 250,200))
        self.temperatureValue2.setFont(font)
        self.temperatureValue2.setStyleSheet("color:rgb(171, 171, 171);")
        self.temperatureValue2.setAlignment(QtCore.Qt.AlignCenter)
        self.temperatureValue2.setObjectName("temperatureValue2")

        self.temperatureValue3 = QtWidgets.QLabel(self.centralWidget)
        self.temperatureValue3.setGeometry(QtCore.QRect(960, 180, 250,200))
        self.temperatureValue3.setFont(font)
        self.temperatureValue3.setStyleSheet("color:rgb(171, 171, 171);")
        self.temperatureValue3.setAlignment(QtCore.Qt.AlignCenter)
        self.temperatureValue3.setObjectName("temperatureValue3")

        font = QtGui.QFont()
        font.setPointSize(297)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.pressureValue.setFont(font)
        self.pressureValue.setStyleSheet("color:rgb(171, 171, 171);")
        self.pressureValue.setAlignment(QtCore.Qt.AlignCenter)
        self.pressureValue.setObjectName("pressureValue")
        self.pressureUnitsLabel = QtWidgets.QLabel(self.centralWidget)
        self.pressureUnitsLabel.setGeometry(QtCore.QRect(450, 450, 400, 91))

        font = QtGui.QFont()
        font.setPointSize(55)
        self.pressureUnitsLabel.setFont(font)
        self.pressureUnitsLabel.setStyleSheet("color:rgb(171, 171, 171);")
        self.pressureUnitsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.pressureUnitsLabel.setObjectName("pressureUnitsLabel")
        self.temperatureUnitsLabel = QtWidgets.QLabel(self.centralWidget)
        self.temperatureUnitsLabel.setGeometry(QtCore.QRect(450, 405, 400, 111))
        font = QtGui.QFont()
        font.setPointSize(95)
        self.temperatureUnitsLabel.setFont(font)
        self.temperatureUnitsLabel.setStyleSheet("color:rgb(171, 171, 171);")
        self.temperatureUnitsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.temperatureUnitsLabel.setObjectName("temperatureUnitsLabel")
        self.temperatureUnitsLabel.hide()
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.GUI_Title.setText(_translate("MainWindow", "Pressure Monitor"))
        self.upperCalLabel.setText(_translate("MainWindow", "Upper Pressure Point"))
        self.lowerCalLabel.setText(_translate("MainWindow", "Lower Pressure Point"))
        self.pressTempToggleButton.setText(_translate("MainWindow", "Temperature"))
        self.numGraphToggleButton.setText(_translate("MainWindow", "Number"))
        self.upperCalButton.setText(_translate("MainWindow", "Set Point"))
        self.lowerCalButton.setText(_translate("MainWindow", "Set Point"))
        self.calibrateButton.setText(_translate("MainWindow", "Calibrate"))
        self.logButton.setText(_translate("MainWindow", "Record"))
        self.pressureValue.setText(_translate("MainWindow", "000"))
        self.pressureUnitsLabel.setText(_translate("MainWindow", "mmHg"))
        self.temperatureValue0.setText(_translate("MainWindow", "0"))
        self.temperatureUnitsLabel.setText(_translate("MainWindow", "°C"))
        self.tempLabel0.setText(_translate("MainWindow", "Probe 1"))
        self.tempLabel1.setText(_translate("MainWindow", "Probe 2"))
        self.tempLabel2.setText(_translate("MainWindow", "Probe 3"))
        self.tempLabel3.setText(_translate("MainWindow", "Probe 4"))

from pressurePlotter import CustomPressWidget
from temperaturePlotter import CustomTempWidget
